# How long before a player is banned, seconds.
ban-time: 10

# How should we ban the player? 'IP' or 'NAME'?
ban-type: NAME

# How many days to ban for? 'null' for a permanent ban.
ban-days: 30

# Flight properties.
flight:
  # Is the check enabled?
  enabled: true

  # Should we cancel the check?
  cancel: true

  # Cancel VL, if you want the check to cancel everytime set this to 0.
  cancel-vl: 0

  # What VL should we ban at? Set this to -1 to disable banning.
  ban: -1

  # What VL should we notify at? '1' indicates everytime,
  # '2' Will indicate we should only alert if the VL is divisible by 2.
  notify: 1

  # What is the max height we can jump?
  max-jump: 0.42

  # Whats the max amount of time we can hover for?
  max-hover-time: 1

  # How fast can we climb a ladder?
  ascend-ladder: 0.1176000022888184

  # How fast can we descend on a ladder?
  descend-ladder: 0.1500000000000036

  # Max time we can ascend.
  ascend-time: 7

morepackets:
  # Is the check enabled?
  enabled: true

  # Should we cancel the check?
  cancel: true

  # Cancel VL, if you want the check to cancel everytime set this to 0.
  cancel-vl: 0

  # What VL should we ban at? Set this to -1 to disable banning.
  ban: -1

  # What VL should we notify at? '1' indicates everytime,
  # '2' Will indicate we should only alert if the VL is divisible by 2.
  notify: 1

  # Max amount of packets allowed per second. (Modify this if you have laggy players.)
  max-packets: 23

nofall:
  # Is the check enabled?
  enabled: true

  # Should we cancel the check?
  cancel: true

  # Cancel VL, if you want the check to cancel everytime set this to 0.
  cancel-vl: 0

  # What VL should we ban at? Set this to -1 to disable banning.
  ban: -1

  # What VL should we notify at? '1' indicates everytime,
  # '2' Will indicate we should only alert if the VL is divisible by 2.
  notify: 1

