main: me.vrekt.arc.Arc
name: Arc
version: 2.0
depend: [ProtocolLib]

permissions:
  arc.violations:
    description: Allows a player to see if another player fails a check.
  arc.bypass:
    description: Allows a player to bypass all checks.
  arc.administrator:
    description: Allows a player to manage Arc.

commands:
  arc:
   description: Base command for Arc management.
   usage: /arc